version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    restart: always
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src/helloworld:/var/www/html/helloworld
  php:
    container_name: php
    build: ./docker/php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./src/helloworld:/var/www/html/helloworld
    working_dir: /var/www/html/helloworld
  composer:
    container_name: composer
    image: composer/composer
    volumes:
      - ./src/helloworld:/var/www/html/helloworld
    working_dir: /var/www/html/helloworld
    command: install
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret123'
      MYSQL_DATABASE: helloworld
      MYSQL_USER: helloworld
      MYSQL_PASSWORD: 'secret123'
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80